# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sample
  pod 'apptentive-ios'

  target 'sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sample-tvOS

  target 'sample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
