# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for sample
  pod 'apptentive-ios', '5.2.14'

end
